language: android
jdk: oraclejdk8
dist: xenial
git:
  depth: 1
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'
script:
  - chmod 777 gradlew
  - ./gradlew clean assemblePureDebug
after_success:
  - bash <(curl -s https://codecov.io/bash)
